CC=gcc
CFLAGS=-lcrypto -lssl
RELEASE_PATH = ./release/linux/64

default: build

make_release_path:
	mkdir -p ${RELEASE_PATH}

clean:
	rm -rf ${RELEASE_PATH}

build: make_release_path
	$(CC) ./src/main.c $(CFLAGS) -o ${RELEASE_PATH}/main
